SPRING_PROFILES_ACTIVE: dev
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cache:
    redis:
      enable-statistics: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
jwt:
  access:
    token:
      expiry: 60000000
      secret:
        key: 357638792F423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B58
  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key: 7134743777217A25432A462D4A614E645267556B58703272357538782F413F44
logging:
  level:
    ch.qos.logback: ERROR
    org.springframework: INFO
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---
#LOGS:  '/home/elshod/apps/application_logs'
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/anime
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 25
    username: 65745533e8877a
    password: d011add8b02d5f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


firebase:
  type: service_account
  project_id: anime-uz
  private_key_id: 862e1a25061ec9313f6d1b770f4ee1a257ce9977
  private_key: -----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCmLdqJufVv8eQ9\ndFB47MS9jsdsksixHtnD4l7cr8rYRlLl7voNL6Xzczs6ImhoT+5tiBznF7z5qS+p\nzEZ55PPKYHQKClXwfN3akNi5NvsziLYZZK0919vdDisxe7LskRt8hgC7ULzAB5f9\nG2FcANKbytoRDdyTfgIsi/HwlinBmaXcROQhboHLtGNNCrLDP/xaZx2X1PfaLWvE\nTp/U9wycm4Y/sru5bM4wnbdPA1hi4+4k8hIsj08JaDsfJb01elvJzoE6QptTLSfh\nwUnyxixiDHDd1Q2eFA7XQaj+wHEyRI26IfR+VvG7CnBGxGkqUIm0NMpzLeY5c8cJ\nBNEZw2TBAgMBAAECggEABXWm8wSrI74DmMHGJYzo0036Lw7c/VW1Q5ZftbooTMX1\nsgRxjmaY+gg4g0rPWZL7szlIMs7wuFaWwGo7zAQpvsW/tjc79tJRYx2EY0RjSSCG\nFAw+1VPuzyLIqD/nQ1aqm6MW6dCHnPr64zfHsXM8+B2YX7xP+YAHsAE6hgQW89tr\n69F7vawxYyQvhPR2hr7Wq6IxglAfbgsfcd9C/hJeYe+hIlOZxw6K4rqPLApeQrLc\nVGhBAQnXnNU59SdqsNBOvWQJGvym7lhotF+OMqeQquILcuMznpV5U8u3q+l0ui/0\nKOqW7zouBkNFER7FZHX5So1XqjXBOyCwqNzbI8m6+QKBgQDkmp9bfN+pysRZJe/s\ncaVIbdJasaWIBjejyLljKhurmi3uD0KSihe3geADbNZs99mE7HGc+Vroz+nFAvnD\nRgM7RRTYvXwrFqfNinKemdawcgP4tYdyk3zKkZm3QQKKODDV2jywShdmFF+KR+v2\nA0379ttxzAbD2ZKIbk+roGnbqQKBgQC6GBav2Gt2/RRnLEOLL/Up5yhieRTopu+7\n0315Q+TSYtZVmOfgss8odISOBI/Gvs3UY6qSnznZwbl1i23/WPjDTzQm9hvNI8tk\nYk3X7HSQ2tRO97sQdnbCSSDhmbNsOnuXybEPBPzrHgUd63wM7tE9rKDK3LId8dmh\ndftALdIvWQKBgQCus4u9Ov0ioRbUmi10oJUTePoc3U4HWdkDjc4/flqPFdCr8XWK\nz4W4c8RiWba0p+TPtHJO6DEVYm7gZJnDJaoqjWyVBpnxw+qRJZDaq+5qAXgPhYrx\ngM0JcaPra/8o6jBH/fQLNVQUatVos/YbmALs34ZsvOMeoRNeuA6itoCvoQKBgQCv\neK9LuCH83L40WsSFpf7iOBkYYVuZ1G8RCGazxZUp3BCGPdvHQFOdreCfmSWJHbkv\nn5rjDkiaT9T0RTi/IcHPSAvBASdN04ahbSBBjbCMNgsjOuykpU9t+06J60gHsU2A\n3qmZo/ZoLLJeeAFMoJOkN/aV0mwRWE8BtCHpbktWYQKBgDi3A7AMVH96Mg9VupMH\nvo/iy2rq6Ey0sk17VOFZ5rVi3e5o44KnQP6L+FvPEj73QetU4H9Gpo8lpMS/v4ZR\n2kgQ0yq3ieCqJjZnJXYBMoPSBQNxXFkxsvQ2uFEqOFE4nXKeljVgfjmv0NVupJ1p\nHOYd/Monr7pnf5KtmUYoR0Xy\n-----END PRIVATE KEY-----\n
  client_email: firebase-adminsdk-ntd7w@anime-uz.iam.gserviceaccount.com
  client_id: 108083323564605992268
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-ntd7w%40anime-uz.iam.gserviceaccount.com